// export const interviewData = [
//   {
//     id: 1,
//     summary: "1st Round",
//     interviewer: "Karan",
//     start: "2025-03-10T00:01:00+05:30",
//     end: "2025-03-10T01:40:00+05:30",
//     link: "http://www.hhh.com",
//     user_det: [
//       {
//         id: 1,
//         candidate: {
//           candidate_firstName: "Juni",
//           candidate_lastName: "Kin",
//         },
//         handled_by: {
//           firstName: "Prin",
//         },
//         job_id: {
//           jobRequest_Title: "Node Developer",
//         },
//       },
//     ],
//   },
//   {
//     id: 2,
//     summary: "2nd Round",
//     title: "Next.js Engineer",
//     interviewer: "Ravi",
//     start: "2025-03-16T18:00:00+05:30",
//     end: "2025-03-16T20:40:00+05:30",
//     link: "http://www.hhh.com",
//     user_det: [
//       {
//         id: 1,
//         candidate: {
//           candidate_firstName: "Mohan",
//           candidate_lastName: "Raj",
//         },
//         handled_by: {
//           firstName: "Vinodhini",
//         },
//         job_id: {
//           jobRequest_Title: "Django Developer",
//         },
//       },
//       {
//         id: 2,
//         candidate: {
//           candidate_firstName: "Test",
//           candidate_lastName: "Here",
//         },
//         handled_by: {
//           firstName: "Kiruba",
//         },
//         job_id: {
//           jobRequest_Title: "Django Developer",
//         },
//       },
//     ],
//   },
// ];

export const interviewData = [
  {
    id: 1,
    summary: "1st Round",
    desc: "1st Round",
    start: "2025-03-18T18:00:00+05:30",
    end: "2025-03-18T18:40:00+05:30",
    attendees: null,
    status: null,
    comment: null,
    score: {
      P: 8,
    },
    link: "http://www.hhh.com",
    user_det: [
      {
        id: 1,
        question_score: null,
        status: null,
        candidate: {
          id: 1,
          candidate_firstName: "mohan",
          candidate_lastName: "raj",
          candidateGender: "male",
          candidateComment: "",
          candidate_email: "mohanrajk@dataterrain.com",
        },
        handled_by: {
          id: 3,
          last_login: null,
          userEmail: "vinodhini_hr@dataterrain.com",
          username: "vinodhini_hr",
          firstName: "Vinodhini",
          lastName: "HR",
          userRole: "hr_employee",
        },
        job_id: {
          id: 11,
          jobRequest_Title: "django developer",
          jobRequest_Role: "software engineer",
          jobRequest_KeySkills: "django",
          jobRequest_Description: "asfffasf",
        },
      },
    ],
    job_id: {
      id: 11,
      jobRequest_Title: "django developer",
      jobRequest_Role: "software engineer",
      jobRequest_KeySkills: "django",
      jobRequest_Description: "asfffasf",
    },
  },
  {
    id: 2,
    summary: "Test",
    desc: "Test",
    start: "2025-03-19T19:00:00+05:30",
    end: "2025-03-19T19:30:00+05:30",
    attendees: null,
    status: null,
    comment: null,
    score: {
      p: 7,
    },
    link: "http://www.hhh.com",
    user_det: [
      {
        id: 1,
        question_score: null,
        status: null,
        candidate: {
          id: 1,
          candidate_firstName: "mohan",
          candidate_lastName: "raj",
          candidateGender: "male",
          candidateComment: "",
          candidate_email: "mohanrajk@dataterrain.com",
        },
        handled_by: {
          id: 3,
          last_login: null,
          userEmail: "vinodhini_hr@dataterrain.com",
          username: "vinodhini_hr",
          firstName: "Vinodhini",
          lastName: "HR",
          userRole: "hr_employee",
        },
        job_id: {
          id: 11,
          jobRequest_Title: "django developer",
          jobRequest_Role: "software engineer",
          jobRequest_KeySkills: "django",
          jobRequest_Description: "asfffasf",
        },
      },
      {
        id: 2,
        question_score: null,
        status: null,
        candidate: {
          id: 2,
          candidate_firstName: "kiruba",
          candidate_lastName: "ravi",
          candidateGender: "male",
          candidateComment: "",
          candidate_email: "kiruba@gmail.com",
        },
        handled_by: {
          id: 3,
          last_login: null,
          userEmail: "vinodhini_hr@dataterrain.com",
          username: "vinodhini_hr",
          firstName: "Vinodhini",
          lastName: "HR",
          userRole: "hr_employee",
        },
        job_id: {
          id: 11,
          jobRequest_Title: "React developer",
          jobRequest_Role: "software engineer",
          jobRequest_KeySkills: "React",
          jobRequest_Description: "Testing",
        },
      },
    ],
    job_id: {
      id: 11,
      jobRequest_Title: "Software developer",
      jobRequest_Role: "software engineer",
      jobRequest_KeySkills: "React",
      jobRequest_Description: "Testing",
    },
  },
  {
    id: 3,
    summary: "2nd Round",
    desc: "2nd Round",
    start: "2025-03-20T20:00:00+05:30",
    end: "2025-03-20T20:30:00+05:30",
    attendees: null,
    status: null,
    comment: null,
    score: {
      o: 6,
    },
    link: "http://www.hhh.com",
    user_det: [
      {
        id: 1,
        question_score: null,
        status: null,
        candidate: {
          id: 1,
          candidate_firstName: "mohan",
          candidate_lastName: "raj",
          candidateGender: "male",
          candidateComment: "",
          candidate_email: "mohanrajk@dataterrain.com",
        },
        handled_by: {
          id: 3,
          last_login: null,
          userEmail: "vinodhini_hr@dataterrain.com",
          username: "vinodhini_hr",
          firstName: "Vinodhini",
          lastName: "HR",
          userRole: "hr_employee",
        },
        job_id: {
          id: 11,
          jobRequest_Title: "django developer",
          jobRequest_Role: "software engineer",
          jobRequest_KeySkills: "django",
          jobRequest_Description: "asfffasf",
        },
      },
      {
        id: 2,
        question_score: null,
        status: null,
        candidate: {
          id: 1,
          candidate_firstName: "Neetha",
          candidate_lastName: "Ran",
          candidateGender: "male",
          candidateComment: "",
          candidate_email: "Neetha@gmail.com",
        },
        handled_by: {
          id: 3,
          last_login: null,
          userEmail: "vinodhini_hr@dataterrain.com",
          username: "vinodhini_hr",
          firstName: "Vinodhini",
          lastName: "HR",
          userRole: "hr_employee",
        },
        job_id: {
          id: 11,
          jobRequest_Title: "Nextjs developer",
          jobRequest_Role: "software engineer",
          jobRequest_KeySkills: "Next",
          jobRequest_Description: "Test",
        },
      },
      {
        id: 3,
        question_score: null,
        status: null,
        candidate: {
          id: 1,
          candidate_firstName: "Jeevan",
          candidate_lastName: "ram",
          candidateGender: "male",
          candidateComment: "",
          candidate_email: "jeevan@gmail.com",
        },
        handled_by: {
          id: 3,
          last_login: null,
          userEmail: "vinodhini_hr@dataterrain.com",
          username: "vinodhini_hr",
          firstName: "Vinodhini",
          lastName: "HR",
          userRole: "hr_employee",
        },
        job_id: {
          id: 11,
          jobRequest_Title: "Node developer",
          jobRequest_Role: "software engineer",
          jobRequest_KeySkills: "node",
          jobRequest_Description: "Test",
        },
      },
    ],
    job_id: {
      id: 11,
      jobRequest_Title: "Software Engineer",
      jobRequest_Role: "software engineer",
      jobRequest_KeySkills: "django",
      jobRequest_Description: "Test",
    },
  },
];
